import os

DISPLAY_WIDTH, DISPLAY_HEIGHT = 1920, 1080
CHROME_VERSION = "116.0.5845.111"
CHROME_PROFILE_PATH = os.path.join(os.getcwd(), "CHROME_PROFILE")
CHROME_PROFILE = rf"--user-data-dir={CHROME_PROFILE_PATH}"

